---
development:
  title:
  body:
test:
  title: Welcome to the <i>test</i> site
  body: This is a <b>test</b> <a href="mailto:fake@princeton.edu">message.</a>
staging:
  title:
  body:
qa:
  title:
  body:
ci:
  title:
  body:
production:
  title:
  body:
